### ISSUE TITLE
How to build with .NET 8?

### ISSUE THREAD

**Issue by LittleCodingFox** [josephmoresena/NativeAOT-AndroidHelloJniLib#1]
Hello,

There seems to be some instructions missing, do you think you could update the README with instructions for .NET 8?

Thank you very much!

**Comment by josephmoresena** [comment]
I think I've already done that, but if you think it could be more specific I'd be happy to have your help.
In these instructions I am using android_fake_clang script and ANDROID_NDK_ROOT env var to avoid PATH issues. I tested it on macOS, but I think it works on Windows and Linux.

**Comment by LittleCodingFox** [comment]
Oh, the formatting confused me because I thought the instructions to build were for BFlat only. Maybe you can adjust the readme headers to be clearer?

Thank you!

**Comment by josephmoresena** [comment]
Please check again.

**Comment by LittleCodingFox** [comment]
Perfect, thanks a lot!
