### ISSUE TITLE
Publish with .Net 8 has some issues

### ISSUE THREAD

**Issue by MikaTas** [josephmoresena/NativeAOT-AndroidHelloJniLib#2]
Publish with .Net 8 has some issues:
Windows 10 64bit.

try1:
dotnet publish -r linux-bionic-arm64 -p:DisableUnsupportedError=true -p:PublishAotUsingRuntimePack=true -p:AssemblyName=libhello-jni -p:RemoveSections=true

> error : Requested linker ('./android_fake_clang.cmd') not found in PA
TH. [C:\dev\net8tests\NativeAOT-AndroidHelloJniLib\AndroidHelloJniLib.csproj]

A change to .csproj row 49 - solves the error:
<CppCompilerAndLinker Condition="$(IsWindowsHost) == 'true'">android_fake_clang.cmd</CppCompilerAndLinker>

try2:
dotnet publish ...

error : Symbol stripping tool ('C/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-objcopy') not found in PATH.

A change to .csproj row 55 + adding the path to system env param path - solves the error:
<ObjCopyName Condition="'$(ObjCopyName)' == ''">llvm-objcopy</ObjCopyName>

try3:
dotnet publish ...

error MSB3073: The command "sed -i -z 's/global: _init; _fini;/global: /g;' obj\Release\net8.0\linux-bionic-arm64\
native\libhello-jni.exports" exited with code 9009.

**Comment by josephmoresena** [comment]
Try not to use '-p:RemoveSections=true'. Maybe we should prevent it from being used on a Windows host.
The purpose of that parameter is to eliminate the _init and _fini lines from the exports file, the zed command looks for that pattern and replaces it with empty ones. https://github.com/dotnet/runtime/issues/92272#issuecomment-1732352537

**Comment by keyboqrd** [comment]
I am having exactly the same errors

Error from "try1" and "try2" can be bypassed by adding directories to PATH, and using only commands instead of paths.
Error from "try3" indeed disappeared after removing `-p:RemoveSections=true`

Then I am having:

```
ld.lld : error : version script assignment of 'V1.0' to symbol '_init' failed: symbol not defined
ld.lld : error : version script assignment of 'V1.0' to symbol '_fini' failed: symbol not defined
```

**Comment by josephmoresena** [comment]
> I am having exactly the same errors
> 
> Error from "try1" and "try2" can be bypassed by adding directories to PATH, and using only commands instead of paths. Error from "try3" indeed disappeared after removing `-p:RemoveSections=true`
> 
> Then I am having:
> 
> ```
> ld.lld : error : version script assignment of 'V1.0' to symbol '_init' failed: symbol not defined
> ld.lld : error : version script assignment of 'V1.0' to symbol '_fini' failed: symbol not defined
> ```

Is this happening with the latest commit (branch)? What host OS are you using?

**Comment by josephmoresena** [comment]
Please pull the latest commit. I've fixed Windows build using [BionicNativeAot.targets file](https://github.com/josephmoresena/NativeAOT-AndroidHelloJniLib/blob/main/BionicNativeAot.targets).

**Comment by keyboqrd** [comment]
> Please pull the latest commit. I've fixed Windows build using [BionicNativeAot.targets file](https://github.com/josephmoresena/NativeAOT-AndroidHelloJniLib/blob/main/BionicNativeAot.targets).

Yes, it's good now. Sorry for the late reply and thank you
