### ISSUE TITLE
bflat build has some issues

### ISSUE THREAD

**Issue by MikaTas** [josephmoresena/NativeAOT-AndroidHelloJniLib#3]
bflat build -r BFlatSupport/Rxmxnx.PInvoke.Extensions.dll --no-stacktrace-data --no-globalization --no-exception-messages -Os --no-pie --separate-symbols --os:linux --arch:arm64 --libc:bionic -o:libhello-jni.so

C:\dev\net8tests\NativeAOT-AndroidHelloJniLib\obj\Release\net8.0\linux-bionic-arm64\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute

**Comment by josephmoresena** [comment]
Delete \bin and \obj. BFlat includes by default those folders to compile.
