### ISSUE TITLE
A port of this guide for console apps

### ISSUE THREAD

**Issue by Bip901** [josephmoresena/NativeAOT-AndroidHelloJniLib#4]
Hi, not sure where to put this, but I created a simplified version of this guide for regular console apps (to produce ELF executables rather than libraries)
Someone may find this useful:
https://gist.github.com/Bip901/af46447d7e7b0b9647f0841946979e0e

**Comment by josephmoresena** [comment]
From that console application is possible to use Invocation API?

**Comment by Bip901** [comment]
Do you mean P/Invoke? Yeah, it's running regular C#

**Comment by josephmoresena** [comment]
No, this project is not a test of the Bionic + NativeAOT compilation, it is a test of the interoperability of JNI with NativeAOT, even using Bionic (Android).

What I mean by Invocation API is: [The Invocation API](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/invocation.html)

**Comment by Bip901** [comment]
I see.
In that case, no, my console application wouldn't be able to use Invocation API without some extra tweaks.

This repo just happens to be the first search result when looking for instructions for Bionic + NativeAOT so I assumed other users are in the same boat as I.
