### ISSUE TITLE
Why the JBoolean falseByte is 2 ?

### ISSUE THREAD

**Issue by EjiHuang** [josephmoresena/NativeAOT-AndroidHelloJniLib#7]
```
public static JBoolean afunc(){
    return false;
}
```
Hi, Thank you for sharing the project. 
Currently I have a problem. When I use JBoolean as the return value, it is always true. I found in jni's code that the returned value is 2. So, why is it set to 2 instead of 0? When I set falseByte to 0, the jni code works fine.

```
private static readonly Byte trueByte = 1;
private static readonly Byte falseByte = 0; // old is 2
```

**Comment by josephmoresena** [comment]
Yes is a typo. jni.h

    #define JNI_FALSE 0
    #define JNI_TRUE 1

By now I'm working in a full [JNI solution](https://github.com/josephmoresena/Rxmxnx.JNetInterface) many bugs here may have now been resolved there.

**Comment by EjiHuang** [comment]
OK, thank you.
